{{- if and .Values.secret (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kravn.fullname" . }}-secret
  labels:
    {{- include "kravn.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecretKey }}: {{ .Values.secret | quote }}
{{- end }}
